### ISSUE TITLE
WS getting stuck while scanning nexus repo

### ISSUE THREAD

**Issue by karan6190** [whitesource-ps/ws-nexus-integration#10]
WS is able to authenticate nexus. As my interactive mode is *“on”*, I am expecting to scan a particular docker image [which is inside docker-group repo, under particular product name] say like **xxxx.nexus.com/<product_name>/<imag_name>** 

But WS simply got stuck while selecting the Repository where my Image is stored.

**Comment by NatalyaDalid** [comment]
Hi Karan,

Thank you for reaching out to us.

The docker format is currently not supported and we recently provided a fix for not displaying the formats that are not
supported. Please download the latest version.

Let us know the importance of this feature so we can evaluate it.

Thank you, 
WhiteSource PS team

**Comment by karan6190** [comment]
Thanks, @NatalyaDalid, basically I was trying for Docker only, will check out the latest version.

Any idea, when can we have docker format?

**Comment by NatalyaDalid** [comment]
Hi Karan, we are currently investigating adding this functionality. We'll update you about the progress next week.

**Comment by tamari-oz** [comment]
Hi @karan6190,
Release [0.2](https://github.com/whitesource-ps/ws-nexus-integration/releases/tag/v0.2) contains support for Docker images on Nexus.
As WhiteSource Unified Agent, The tool assumes that Docker Daemon is installed and running on the host.
The tool will download the images from Nexus Registry.

Let us know if have any questions.

Oz
