### ISSUE TITLE
[Question] [ws-nexus-integration] How does it work for offline??

### ISSUE THREAD

**Issue by RinaGSS** [whitesource-ps/ws-nexus-integration#57]
I used nexus On-Prem. Does Mend generate update-request.txt??
How will Mend upload the results?

BR,
Rina

**Comment by rammatzkvosky** [comment]
Hi @RinaGSS ,

Mend integration with nexus doesn't generate `update-request.txt` as it works by default with `offline=False`
Meaning the scan results are sent directly to your Mend application.


To scan in an offline mode ( create `update-request.txt` in the end of the scan) - please set the `WS_OFFLINE` environment variable to `True`.
It will generate the `update-request.txt` in the tmp directory that you will need to upload later on :
`/tmp/ws-nexus-integration/whitesource/update-request.txt`

For example : 
![image](https://user-images.githubusercontent.com/41573396/205929004-75f06a84-2fd1-4e75-8a8b-71db07b33705.png)

**Comment by RinaGSS** [comment]
Hi @rammatzkvosky 

Where is "WS_OFFLINE"?? 
In the tmp\ws-nexus-integration-22.10.1\config\params.config?? 
There is no offline parameter here.
